apiVersion: v1
kind: Service
metadata:
  name: todo-mysql
  namespace: todo-prod
  labels:
    app: todo-mysql
spec:
  clusterIP: None
  selector:
    app: todo-mysql
  ports:
    - port: 3306
      targetPort: 3306
